<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ContactPersonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contacts = [
            // Department of Commerce and Industries
            [
                'name' => 'Shri Rajat Kumar, IAS',
                'designation' => 'Secretary',
                'email' => 'secycommind.cg@gov.in',
                'category' => 'dept-commerce',
            ],
            [
                'name' => 'Smt Rena Jameel, IAS',
                'designation' => 'Deputy Secretary',
                'category' => 'dept-commerce',
            ],
            [
                'name' => 'Shri Umesh Patel',
                'designation' => 'Deputy Secretary',
                'email' => 'mantralayaindustry@gmail.com',
                'category' => 'dept-commerce',
            ],
            [
                'name' => 'Shri Sanjay Rane',
                'designation' => 'OSD',
                'mobile' => '9926180334',
                'category' => 'dept-commerce',
            ],
            [
                'name' => 'Shri ML Pawar',
                'designation' => 'Under Secretary',
                'email' => 'mantralayaindustry@gmail.com',
                'category' => 'dept-commerce',
            ],
            // Directorate of Industries
            [
                'name' => 'Shri Prabhat Malik, IAS',
                'designation' => 'Director',
                'email' => 'dtic-directorate.cg@gov.in',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Shiv Kumar Rathore',
                'designation' => 'Additional Director',
                'mobile' => '9424257676',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Sanjay Gajghate',
                'designation' => 'Additional Director',
                'mobile' => '9926147385',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri D L Pusam',
                'designation' => 'Joint Director',
                'mobile' => '7587218617',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri L K Lakra',
                'designation' => 'Joint Director',
                'mobile' => '7000875106',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Manisha Anil Nagraj',
                'designation' => 'Deputy Director',
                'mobile' => '7024178277',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Amey Tripathi',
                'designation' => 'Deputy Director',
                'sectors' => 'Pharmaceuticals, Biotechnology, BioEthenol Green Hydrogen, Compressed Bio gas, GCC',
                'mobile' => '8349389246',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Prafull Kumar Sahu',
                'designation' => 'Deputy Director',
                'sectors' => 'IT, ITeS, Semiconductor,BPO',
                'mobile' => '8884322242',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Jageshwar Kumar Sahu',
                'designation' => 'Deputy Director',
                'sectors' => 'Private Industrial Parks, SEZs,Logistics, Export',
                'mobile' => '7999865016',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Rituraj Tamrakar',
                'designation' => 'Deputy Director',
                'sectors' => 'AI,Robotics,GPU, Electricals and Electronics, EV, Aerospace and Defence',
                'mobile' => '9584556704',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Vishwajeet Singh',
                'designation' => 'Deputy Director',
                'sectors' => 'Steel, Engineering,Automobile',
                'mobile' => '6262256560',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Rajeshwari Shukla',
                'designation' => 'Deputy Director',
                'mobile' => '7415552796',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Mausamee Raha',
                'designation' => 'Deputy Director',
                'sectors' => 'Gems and Jewellery, Sports Goods,Tourism, Wellness, Entertainment',
                'mobile' => '7974437665',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Garima Pandey',
                'designation' => 'Deputy Director',
                'mobile' => '7000597676',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Mrinalini Singh Thakur',
                'designation' => 'Assistant Director',
                'sectors' => 'Toy and Footwear, Chemicals and Paints',
                'mobile' => '7024446331',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Chandra Kishore Ureti',
                'designation' => 'Assistant Director',
                'sectors' => 'Textile, Furniture',
                'mobile' => '9827791766',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Bhoopendra Gaur',
                'designation' => 'Assistant Director',
                'mobile' => '7999810361',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Rekha Kshatriya',
                'designation' => 'Assistant Director',
                'mobile' => '8839280862',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Surya Prakash Rawte',
                'designation' => 'Assistant Director',
                'mobile' => '9806050490',
                'category' => 'directorate',
            ],
            [
                'name' => 'Shri Pranchal Sao',
                'designation' => 'Assistant Director',
                'mobile' => '9575030433',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Ameshwari Sahu',
                'designation' => 'Assistant Director',
                'sectors' => 'Forest Based Produces,Agro and Food Processing, Dairy',
                'mobile' => '9754432072',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Vidya Bhandari',
                'designation' => 'Assistant Director',
                'mobile' => '7987045306',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Rubi Salame',
                'designation' => 'Assistant Director',
                'mobile' => '7000374629',
                'category' => 'directorate',
            ],
            [
                'name' => 'Parvati Thakur',
                'designation' => 'Assistant Director',
                'mobile' => '9406019547',
                'category' => 'directorate',
            ],
            [
                'name' => 'Smt Saroj Jhariya',
                'designation' => 'Asisitance Director',
                'mobile' => '9425528375',
                'category' => 'directorate',
            ],
            // SIPB
            [
                'name' => 'Shri Sanjay Gajghate',
                'designation' => 'Additional Director',
                'mobile' => '9926147385',
                'category' => 'sipb',
            ],
            [
                'name' => 'Shri KK Shrivastava',
                'designation' => 'Deputy Director',
                'mobile' => '9893376981',
                'category' => 'sipb',
            ],
            [
                'name' => 'Smt Suman Dewangan',
                'designation' => 'Deputy Director',
                'sectors' => 'Startup',
                'mobile' => '7999453046',
                'category' => 'sipb',
            ],
            [
                'name' => 'Smt Prachi Lal',
                'designation' => 'Assistant Director',
                'category' => 'sipb',
            ],
            [
                'name' => 'Smt Shirin Dewangan',
                'designation' => 'Assistant Director',
                'mobile' => '9907166922',
                'category' => 'sipb',
            ],
            // DTIC
            [
                'name' => 'Shri M S Paikra',
                'designation' => 'Chief General Manager',
                'email' => 'dtic-raipur.cg@gov.in',
                'mobile' => '9926480995',
                'category' => 'dtic',
                'location' => 'DTIC-Raipur',
            ],
            [
                'name' => 'Shri CR Tekkam',
                'designation' => 'Chief General Manager',
                'email' => 'dtic-bilaspur.cg@gov.in',
                'mobile' => '9425262623',
                'category' => 'dtic',
                'location' => 'DTIC-Bilaspur',
            ],
            [
                'name' => 'Shri Bhola Ram Nikunj',
                'designation' => 'Chief General Manager',
                'email' => 'dtic-durg.cg@gov.in',
                'mobile' => '9406253815',
                'category' => 'dtic',
                'location' => 'DTIC-Durg',
            ],
            [
                'name' => 'Shri Ajit Sundar Bilung',
                'designation' => 'Chief General Manager',
                'email' => 'dtic-jagdalpur.cg@gov.in',
                'mobile' => '9424127142',
                'category' => 'dtic',
                'location' => 'DTIC-Jagdalpur',
            ],
            [
                'name' => 'Smt Anju Nayak',
                'designation' => 'Chief General Manager (Incharge)',
                'email' => 'dtic-raigarh.cg@gov.in',
                'mobile' => '9752515837',
                'category' => 'dtic',
                'location' => 'DTIC-Raigarh',
            ],
            [
                'name' => 'Shri Vinay Kumar Tegar',
                'designation' => 'General Manager',
                'email' => 'dtic-koria.cg@gov.in',
                'mobile' => '7693886234',
                'category' => 'dtic',
                'location' => 'DTIC-Koria',
            ],
            [
                'name' => 'Shri Lokpal Khandekar',
                'designation' => 'General Manager',
                'email' => 'dtic-dhamtari.cg@gov.in',
                'mobile' => '8303285157',
                'category' => 'dtic',
                'location' => 'DTIC-Dhamtari',
            ],
            [
                'name' => 'Shri Xavier Toppo',
                'designation' => 'General Manager',
                'email' => 'dtic-janjgir.cg@gov.in',
                'mobile' => '9301341840',
                'category' => 'dtic',
                'location' => 'DTIC-Janjgir-Champa',
            ],
            [
                'name' => 'Shri Ankur Gupta',
                'designation' => 'General Manager',
                'email' => 'dtic-surguja.cg@gov.in',
                'mobile' => '8839262719',
                'category' => 'dtic',
                'location' => 'DTIC-Surguja',
            ],
            [
                'name' => 'Mitesh Duge',
                'designation' => 'General Manager',
                'email' => 'dtic-kabirdham.cg@gov.in',
                'mobile' => '9907539736',
                'category' => 'dtic',
                'location' => 'DTIC-Kabirdham',
            ],
            [
                'name' => 'Shri Chandra Deo Prasad',
                'designation' => 'General Manager',
                'email' => 'dtic-bilaspur.cg@gov.in',
                'mobile' => '9753525457',
                'category' => 'dtic',
                'location' => 'DTIC-Bilaspur',
            ],
            [
                'name' => 'Shri Sanu V Varghese',
                'designation' => 'General Manager',
                'email' => 'dtic-rajnandgaon.cg@gov.in',
                'mobile' => '9826816250',
                'category' => 'dtic',
                'location' => 'DTIC-Rajnandgaon',
            ],
            [
                'name' => 'Shri Rakesh Kumar Chourasia',
                'designation' => 'General Manager',
                'email' => 'dtic-bemetara.cg@gov.in',
                'mobile' => '7000715716',
                'category' => 'dtic',
                'location' => 'DTIC-Bemetara',
            ],
            [
                'name' => 'Shri Santosh Kumar Dhurve',
                'designation' => 'General Manager',
                'email' => 'dtic-bilaspur.cg@gov.in',
                'mobile' => '9424152638',
                'category' => 'dtic',
                'location' => 'DTIC-Bilaspur',
            ],
            [
                'name' => 'Shri San Bihari Ram',
                'designation' => 'General Manager',
                'email' => 'dtic-raipur.cg@gov.in',
                'mobile' => '9826128566',
                'category' => 'dtic',
                'location' => 'DTIC-Raipur',
            ],
            [
                'name' => 'Smt Kachita Derro',
                'designation' => 'General Manager',
                'email' => 'dtic-bilaspur.cg@gov.in',
                'mobile' => '9179125384',
                'category' => 'dtic',
                'location' => 'DTIC-Bilaspur',
            ],
            [
                'name' => 'Shri K. S. Meena',
                'designation' => 'General Manager',
                'email' => 'dtic-narayanpur.cg@gov.in',
                'mobile' => '9407647947',
                'category' => 'dtic',
                'location' => 'DTIC-Narayanpur',
            ],
            [
                'name' => 'Shri Vijay Kare',
                'designation' => 'General Manager',
                'email' => 'dtic-korba.cg@gov.in',
                'mobile' => '8109363862',
                'category' => 'dtic',
                'location' => 'DTIC-Korba',
            ],
            [
                'name' => 'Smt Vaishali Janardan',
                'designation' => 'General Manager',
                'email' => 'dtic-durg.cg@gov.in',
                'mobile' => '8965028348',
                'category' => 'dtic',
                'location' => 'DTIC-Durg',
            ],
            [
                'name' => 'Shri Mohan Lal Sahu',
                'designation' => 'General Manager',
                'email' => 'dtic-mahasamund.cg@gov.in',
                'mobile' => '9826756967',
                'category' => 'dtic',
                'location' => 'DTIC-Mahasamund',
            ],
            [
                'name' => 'Shri Tankeswer Dewangan',
                'designation' => 'General Manager',
                'email' => 'dtic-kanker.cg@gov.in',
                'mobile' => '9584987664',
                'category' => 'dtic',
                'location' => 'DTIC-Kanker',
            ],
            [
                'name' => 'Shri Manish Bhagat',
                'designation' => 'General Manager',
                'email' => 'dtic-jashpur.cg@gov.in',
                'mobile' => '7693949347',
                'category' => 'dtic',
                'location' => 'DTIC-Jashpur',
            ],
            [
                'name' => 'Shri Himalaya Sethiya',
                'designation' => 'General Manager',
                'email' => 'dtic-kondagaon.cg@gov.in',
                'mobile' => '7987310248',
                'category' => 'dtic',
                'location' => 'DTIC-Kondagaon',
            ],
            [
                'name' => 'Shri Ram Khandelwal',
                'designation' => 'General Manager',
                'email' => 'dticraipur@gmail.com',
                'mobile' => '7974566203',
                'category' => 'dtic',
                'location' => 'DTIC-Raipur',
            ],
            [
                'name' => 'Smt Mitwa Bara',
                'designation' => 'General Manager',
                'email' => 'dtic-dantewada.cg@gov.in',
                'mobile' => '9826765733',
                'category' => 'dtic',
                'location' => 'DTIC-Dantewada',
            ],
            [
                'name' => 'Shri Swatantra Singh',
                'designation' => 'General Manager',
                'email' => 'dtic-durg.cg@gov.in',
                'mobile' => '9993241360',
                'category' => 'dtic',
                'location' => 'DTIC-Durg',
            ],
            [
                'name' => 'Shri Kamal Singh Meena',
                'designation' => 'General Manager',
                'email' => 'dtic-narayanpur.cg@gov.in',
                'mobile' => '7987626095',
                'category' => 'dtic',
                'location' => 'DTIC-Narayanpur',
            ],
            [
                'name' => 'Shri Pukul Ram Khandelwal',
                'designation' => 'General Manager',
                'email' => 'dtic-bijapur.cg@gov.in',
                'mobile' => '9993263947',
                'category' => 'dtic',
                'location' => 'DTIC-Bijapur',
            ],
            [
                'name' => 'Smt Guneshvari Sahu',
                'designation' => 'General Manager',
                'email' => 'dtic-balodabazar.cg@gov.in',
                'mobile' => '7828808098',
                'category' => 'dtic',
                'location' => 'DTIC-Balodabazar',
            ],
            [
                'name' => 'Shri Deenbandhu Dhruw',
                'designation' => 'General Manager',
                'email' => 'dtic-gariyaband.cg@gov.in',
                'mobile' => '9424219565',
                'category' => 'dtic',
                'location' => 'DTIC-Gariyaband',
            ],
            [
                'name' => 'Shri Prabhat Singh',
                'designation' => 'General Manager',
                'email' => 'dtic-mungeli.cg@gov.in',
                'mobile' => '8602024849',
                'category' => 'dtic',
                'location' => 'DTIC-Mungeli',
            ],
            [
                'name' => 'Gopal Rao',
                'designation' => 'General Manager',
                'email' => 'dtic-balod.cg@gov.in',
                'mobile' => '7771930360',
                'category' => 'dtic',
                'location' => 'DTIC-Balod',
            ],
            [
                'name' => 'Shri Amar Singh',
                'designation' => 'General Manager',
                'email' => 'dtic-balrampur.cg@gov.in',
                'mobile' => '9993077811',
                'category' => 'dtic',
                'location' => 'DTIC-Balrampur',
            ],
            [
                'name' => 'Shri Philip Tigga',
                'designation' => 'General Manager',
                'email' => 'dtic-surajpur.cg@gov.in',
                'mobile' => '9424180536',
                'category' => 'dtic',
                'location' => 'DTIC-Surajpur',
            ],
            [
                'name' => 'Shri L P Gupta',
                'designation' => 'General Manager',
                'email' => 'dtic-gpm@cg.gov.in',
                'mobile' => '7693824393',
                'category' => 'dtic',
                'location' => 'DTIC-Gaurella-Pendra-Marwahi',
            ],
            [
                'name' => 'Shri Ram Kumar Gupta',
                'designation' => 'General Manager',
                'email' => 'dtic-mmac@cg.gov.in',
                'mobile' => '9993135588',
                'category' => 'dtic',
                'location' => 'DTIC-Mohla-Manpur-Ambagarh-Chowki',
            ],
            [
                'name' => 'Shri Pranay Kumar Baghel',
                'designation' => 'General Manager',
                'email' => 'dtic-kcg@cg.gov.in',
                'mobile' => '9827983452',
                'category' => 'dtic',
                'location' => 'DTIC-Khairagarh-Chuikhadan-Gandai',
            ],
            [
                'name' => 'Shri Kamal Narayan Dhruw',
                'designation' => 'General Manager',
                'email' => 'dtic-sb@cg.gov.in',
                'mobile' => '8109123956',
                'category' => 'dtic',
                'location' => 'DTIC-Sarangarh-Bilaigarh',
            ],
            [
                'name' => 'Smt Vinay Tegar',
                'designation' => 'General Manager (Addi. Charge)',
                'email' => 'dtic-mcb@cg.gov.in',
                'mobile' => '7879879202',
                'category' => 'dtic',
                'location' => 'DTIC-Manendragarh-Chirmari-Bharatpur',
            ],
            [
                'name' => 'Shri Mitwa Bara',
                'designation' => 'General Manager (Addi. Charge)',
                'email' => 'dtic-sukma.cg@gov.in',
                'mobile' => '9826765733',
                'category' => 'dtic',
                'location' => 'DTIC-Sukma',
            ],
            [
                'name' => 'Shri Shobhendra Nayak',
                'designation' => 'General Manager',
                'email' => 'dtic-sakti@cg.gov.in',
                'mobile' => '9654450538',
                'category' => 'dtic',
                'location' => 'DTIC-Sakti',
            ],
            // CSIDC
            [
                'name' => 'Shri Vishwesh Kumar, IFS',
                'designation' => 'Managing Director',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Santosh Bhagat',
                'designation' => 'Executive Director',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Arif Yezdani',
                'designation' => 'Chief General Manager Land Acquisition',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri DS Dhurva',
                'designation' => 'Chief General Manager Revenue and Dues Recovery',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Subhash Bhagat',
                'designation' => 'IC Chief General Manager Marketing',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Hemesh Dewangan',
                'designation' => 'General Manager',
                'mobile' => '9406644666',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri OP Banjare',
                'designation' => 'General Manager Investment Promotion',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Kapil Singh Kushwah',
                'designation' => 'General Manager',
                'mobile' => '7000615954',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Shubham Shukla',
                'designation' => 'General Manager',
                'mobile' => '7697230751',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Ajit Kumar Bhatpahari',
                'designation' => 'General Manager',
                'mobile' => '7000701641',
                'category' => 'csidc',
            ],
            [
                'name' => 'Shri Swapnil Awasthi',
                'designation' => 'Company Secretary',
                'email' => 'csidc.cg@gov.in',
                'category' => 'csidc',
            ],
            // Inspectorate of Boilers
            [
                'name' => 'Shri Gunjan Shukla',
                'designation' => 'Chief Inspector of Boilers',
                'email' => 'cicomind.cg@gov.in',
                'mobile' => '9424144267',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Phanendra Bhoi',
                'designation' => 'Deputy Chief Inspector of Boilers',
                'email' => 'fkbhoi@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Ujjwal Gupta',
                'designation' => 'Senior Inspector of Boilers',
                'email' => 'ujjwal@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Nitin Bajpai',
                'designation' => 'Senior Inspector of Boilers',
                'email' => 'ntnbajpai@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Kudan Raj',
                'designation' => 'Senior Inspector of Boilers',
                'email' => 'knd.kt@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Dwarika Verma',
                'designation' => 'Inspector of Boilers',
                'email' => 'dwarikaverma@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Naresh Sonwani',
                'designation' => 'Inspector of Boilers',
                'email' => 'nareshsonwani@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Deepak Kumar',
                'designation' => 'Inspector of Boilers',
                'email' => 'dpk.lahre@gmail.com',
                'category' => 'boiler',
            ],
            [
                'name' => 'Shri Anil Kumar Minj',
                'designation' => 'Inspector of Boilers',
                'email' => 'anilminj@gmail.com',
                'category' => 'boiler',
            ],
            // Registrar Firms and Society
            [
                'name' => 'Smt Padmani Bhoi Sahu , IAS',
                'designation' => 'Registrar',
                'email' => 'dtic@gmail.com',
                'category' => 'registrar',
            ],
            [
                'name' => 'Shri Satish Sharma',
                'designation' => 'Assistant Registrar',
                'mobile' => '9300630009',
                'category' => 'registrar',
            ],
            [
                'name' => 'Shri Pramod Kujur',
                'designation' => 'Assistant Registrar',
                'mobile' => '9755902050',
                'category' => 'registrar',
            ],
            // Investment Commissioner
            [
                'name' => 'Smt Ritu Sain, IAS',
                'designation' => 'Investment Commissioner',
                'email' => 'chhattisgarh-invest@cg.gov.in',
                'category' => 'investment-commissioner',
            ],
            [
                'name' => 'Smt Anjali Patel',
                'designation' => 'General Manager',
                'email' => 'chhattisgarh-invest@cg.gov.in',
                'category' => 'investment-commissioner',
            ],
        ];

        foreach ($contacts as $contact) {
            \App\Models\ContactPerson::create($contact);
        }
    }
}
